// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Make sure you have at least something in your `Query` type.
// If you don't have a query the playground will be unable
// to introspect your schema!
type Query struct {
}

// `Subscription` is where all the subscriptions your clients can
// request. You can use Schema Directives like normal to restrict
// access.
type Subscription struct {
}

// `Time` is a simple type only containing the current time as
// a unix epoch timestamp and a string timestamp.
type Time struct {
	UnixTime  int    `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}
